// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB4WnHzFGsauuxAT7fKrAdSuLDGO2VDCM',
    appId: '1:48114143392:web:5c4c21cdd908a2cd4bf9c5',
    messagingSenderId: '48114143392',
    projectId: 'fir-with-crud-operations-fcb80',
    authDomain: 'fir-with-crud-operations-fcb80.firebaseapp.com',
    storageBucket: 'fir-with-crud-operations-fcb80.firebasestorage.app',
    measurementId: 'G-Q92YKY9BHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5PxnIpR9LLjZzQ-EpJ63rx_9RkFhXrZQ',
    appId: '1:48114143392:android:83070b687e4222564bf9c5',
    messagingSenderId: '48114143392',
    projectId: 'fir-with-crud-operations-fcb80',
    storageBucket: 'fir-with-crud-operations-fcb80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0wRaYakmLZk5umO_ft6bI7LQ998l6nmY',
    appId: '1:48114143392:ios:a2729dc05ed45ded4bf9c5',
    messagingSenderId: '48114143392',
    projectId: 'fir-with-crud-operations-fcb80',
    storageBucket: 'fir-with-crud-operations-fcb80.firebasestorage.app',
    iosBundleId: 'com.example.firebaseWithCrudOperations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0wRaYakmLZk5umO_ft6bI7LQ998l6nmY',
    appId: '1:48114143392:ios:a2729dc05ed45ded4bf9c5',
    messagingSenderId: '48114143392',
    projectId: 'fir-with-crud-operations-fcb80',
    storageBucket: 'fir-with-crud-operations-fcb80.firebasestorage.app',
    iosBundleId: 'com.example.firebaseWithCrudOperations',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB4WnHzFGsauuxAT7fKrAdSuLDGO2VDCM',
    appId: '1:48114143392:web:3d5f33c0b503059b4bf9c5',
    messagingSenderId: '48114143392',
    projectId: 'fir-with-crud-operations-fcb80',
    authDomain: 'fir-with-crud-operations-fcb80.firebaseapp.com',
    storageBucket: 'fir-with-crud-operations-fcb80.firebasestorage.app',
    measurementId: 'G-R4WHGMYKR4',
  );
}
